// Mocks generated by Mockito 5.4.6 from annotations
// in kangal/test/ui/transactions/transactions_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kangal/data/models/category_spend.dart' as _i6;
import 'package:kangal/data/models/daily_spend.dart' as _i5;
import 'package:kangal/data/models/transaction_model.dart' as _i4;
import 'package:kangal/data/repositories/transaction_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTransactionSummary_0 extends _i1.SmartFake
    implements _i2.TransactionSummary {
  _FakeTransactionSummary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i2.TransactionRepository {
  @override
  _i3.Future<List<_i4.TransactionModel>> getAllTransactions(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, [limit, offset]),
            returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
              <_i4.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.TransactionModel>>.value(
                  <_i4.TransactionModel>[],
                ),
          )
          as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<List<_i4.TransactionModel>> getFilteredTransactions({
    required int? limit,
    required int? offset,
    String? searchQuery,
    String? sourceFilter,
    int? categoryFilter,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredTransactions, [], {
              #limit: limit,
              #offset: offset,
              #searchQuery: searchQuery,
              #sourceFilter: sourceFilter,
              #categoryFilter: categoryFilter,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
              <_i4.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.TransactionModel>>.value(
                  <_i4.TransactionModel>[],
                ),
          )
          as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<_i4.TransactionModel?> getTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i3.Future<_i4.TransactionModel?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i4.TransactionModel?>.value(),
          )
          as _i3.Future<_i4.TransactionModel?>);

  @override
  _i3.Future<_i4.TransactionModel?> getTransactionByTransactionId(
    String? txnId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionByTransactionId, [txnId]),
            returnValue: _i3.Future<_i4.TransactionModel?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i4.TransactionModel?>.value(),
          )
          as _i3.Future<_i4.TransactionModel?>);

  @override
  _i3.Future<int> insertTransaction(_i4.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [transaction]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateTransaction(_i4.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.TransactionModel>> getTransactionsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByDateRange, [start, end]),
            returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
              <_i4.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.TransactionModel>>.value(
                  <_i4.TransactionModel>[],
                ),
          )
          as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<List<_i4.TransactionModel>> getTransactionsBySource(
    String? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsBySource, [source]),
            returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
              <_i4.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.TransactionModel>>.value(
                  <_i4.TransactionModel>[],
                ),
          )
          as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<List<_i4.TransactionModel>> searchTransactions(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTransactions, [query]),
            returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
              <_i4.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.TransactionModel>>.value(
                  <_i4.TransactionModel>[],
                ),
          )
          as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<List<_i4.TransactionModel>> getUnsyncedTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTransactions, []),
            returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
              <_i4.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.TransactionModel>>.value(
                  <_i4.TransactionModel>[],
                ),
          )
          as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<_i2.TransactionSummary> getSummary(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, [startDate, endDate]),
            returnValue: _i3.Future<_i2.TransactionSummary>.value(
              _FakeTransactionSummary_0(
                this,
                Invocation.method(#getSummary, [startDate, endDate]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.TransactionSummary>.value(
              _FakeTransactionSummary_0(
                this,
                Invocation.method(#getSummary, [startDate, endDate]),
              ),
            ),
          )
          as _i3.Future<_i2.TransactionSummary>);

  @override
  _i3.Future<List<_i5.DailySpend>> getDailySpend(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySpend, [startDate, endDate]),
            returnValue: _i3.Future<List<_i5.DailySpend>>.value(
              <_i5.DailySpend>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i5.DailySpend>>.value(
              <_i5.DailySpend>[],
            ),
          )
          as _i3.Future<List<_i5.DailySpend>>);

  @override
  _i3.Future<List<_i6.CategorySpend>> getCategorySpend(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCategorySpend, [startDate, endDate]),
            returnValue: _i3.Future<List<_i6.CategorySpend>>.value(
              <_i6.CategorySpend>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i6.CategorySpend>>.value(
                  <_i6.CategorySpend>[],
                ),
          )
          as _i3.Future<List<_i6.CategorySpend>>);

  @override
  _i3.Future<int> reassignCategory(int? oldCategoryId, int? newCategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#reassignCategory, [
              oldCategoryId,
              newCategoryId,
            ]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
