// Mocks generated by Mockito 5.4.6 from annotations
// in kangal/test/ui/dashboard/dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:kangal/data/models/category_spend.dart' as _i4;
import 'package:kangal/data/models/daily_spend.dart' as _i3;
import 'package:kangal/data/repositories/transaction_repository.dart' as _i5;
import 'package:kangal/ui/dashboard/dashboard_view_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateRange_0 extends _i1.SmartFake implements _i2.DateRange {
  _FakeDateRange_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardViewModel extends _i1.Mock
    implements _i2.DashboardViewModel {
  MockDashboardViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.DailySpend> get dailySpend =>
      (super.noSuchMethod(
            Invocation.getter(#dailySpend),
            returnValue: <_i3.DailySpend>[],
          )
          as List<_i3.DailySpend>);

  @override
  List<_i4.CategorySpend> get categorySpend =>
      (super.noSuchMethod(
            Invocation.getter(#categorySpend),
            returnValue: <_i4.CategorySpend>[],
          )
          as List<_i4.CategorySpend>);

  @override
  _i2.DateRange get selectedPeriod =>
      (super.noSuchMethod(
            Invocation.getter(#selectedPeriod),
            returnValue: _FakeDateRange_0(
              this,
              Invocation.getter(#selectedPeriod),
            ),
          )
          as _i2.DateRange);

  @override
  _i2.PeriodPreset get selectedPreset =>
      (super.noSuchMethod(
            Invocation.getter(#selectedPreset),
            returnValue: _i2.PeriodPreset.thisWeek,
          )
          as _i2.PeriodPreset);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set summary(_i5.TransactionSummary? value) => super.noSuchMethod(
    Invocation.setter(#summary, value),
    returnValueForMissingStub: null,
  );

  @override
  set dailySpend(List<_i3.DailySpend>? value) => super.noSuchMethod(
    Invocation.setter(#dailySpend, value),
    returnValueForMissingStub: null,
  );

  @override
  set categorySpend(List<_i4.CategorySpend>? value) => super.noSuchMethod(
    Invocation.setter(#categorySpend, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedPeriod(_i2.DateRange? value) => super.noSuchMethod(
    Invocation.setter(#selectedPeriod, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedPreset(_i2.PeriodPreset? value) => super.noSuchMethod(
    Invocation.setter(#selectedPreset, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void selectPeriod(_i2.PeriodPreset? preset) => super.noSuchMethod(
    Invocation.method(#selectPeriod, [preset]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#loadDashboardData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
