// Mocks generated by Mockito 5.4.6 from annotations
// in kangal/test/ui/settings/rules/rules_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kangal/data/models/category_model.dart' as _i7;
import 'package:kangal/data/models/category_spend.dart' as _i10;
import 'package:kangal/data/models/daily_spend.dart' as _i9;
import 'package:kangal/data/models/rule_model.dart' as _i5;
import 'package:kangal/data/models/transaction_model.dart' as _i8;
import 'package:kangal/data/repositories/category_repository.dart' as _i6;
import 'package:kangal/data/repositories/rule_repository.dart' as _i3;
import 'package:kangal/data/repositories/transaction_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTransactionSummary_0 extends _i1.SmartFake
    implements _i2.TransactionSummary {
  _FakeTransactionSummary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RuleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRuleRepository extends _i1.Mock implements _i3.RuleRepository {
  MockRuleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.RuleModel>> getAllRules() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRules, []),
            returnValue: _i4.Future<List<_i5.RuleModel>>.value(
              <_i5.RuleModel>[],
            ),
          )
          as _i4.Future<List<_i5.RuleModel>>);

  @override
  _i4.Future<_i5.RuleModel?> getRuleById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRuleById, [id]),
            returnValue: _i4.Future<_i5.RuleModel?>.value(),
          )
          as _i4.Future<_i5.RuleModel?>);

  @override
  _i4.Future<int> insertRule(_i5.RuleModel? rule) =>
      (super.noSuchMethod(
            Invocation.method(#insertRule, [rule]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> updateRule(_i5.RuleModel? rule) =>
      (super.noSuchMethod(
            Invocation.method(#updateRule, [rule]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteRule(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRule, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i6.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.CategoryModel>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i4.Future<List<_i7.CategoryModel>>.value(
              <_i7.CategoryModel>[],
            ),
          )
          as _i4.Future<List<_i7.CategoryModel>>);

  @override
  _i4.Future<_i7.CategoryModel?> getCategoryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i4.Future<_i7.CategoryModel?>.value(),
          )
          as _i4.Future<_i7.CategoryModel?>);

  @override
  _i4.Future<int> insertCategory(_i7.CategoryModel? category) =>
      (super.noSuchMethod(
            Invocation.method(#insertCategory, [category]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> updateCategory(_i7.CategoryModel? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.CategoryModel>> getDefaultCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultCategories, []),
            returnValue: _i4.Future<List<_i7.CategoryModel>>.value(
              <_i7.CategoryModel>[],
            ),
          )
          as _i4.Future<List<_i7.CategoryModel>>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i2.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.TransactionModel>> getAllTransactions(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, [limit, offset]),
            returnValue: _i4.Future<List<_i8.TransactionModel>>.value(
              <_i8.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i8.TransactionModel>>);

  @override
  _i4.Future<_i8.TransactionModel?> getTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i4.Future<_i8.TransactionModel?>.value(),
          )
          as _i4.Future<_i8.TransactionModel?>);

  @override
  _i4.Future<_i8.TransactionModel?> getTransactionByTransactionId(
    String? txnId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionByTransactionId, [txnId]),
            returnValue: _i4.Future<_i8.TransactionModel?>.value(),
          )
          as _i4.Future<_i8.TransactionModel?>);

  @override
  _i4.Future<int> insertTransaction(_i8.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [transaction]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> updateTransaction(_i8.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i8.TransactionModel>> getTransactionsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByDateRange, [start, end]),
            returnValue: _i4.Future<List<_i8.TransactionModel>>.value(
              <_i8.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i8.TransactionModel>>);

  @override
  _i4.Future<List<_i8.TransactionModel>> getTransactionsBySource(
    String? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsBySource, [source]),
            returnValue: _i4.Future<List<_i8.TransactionModel>>.value(
              <_i8.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i8.TransactionModel>>);

  @override
  _i4.Future<List<_i8.TransactionModel>> searchTransactions(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTransactions, [query]),
            returnValue: _i4.Future<List<_i8.TransactionModel>>.value(
              <_i8.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i8.TransactionModel>>);

  @override
  _i4.Future<List<_i8.TransactionModel>> getUnsyncedTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTransactions, []),
            returnValue: _i4.Future<List<_i8.TransactionModel>>.value(
              <_i8.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i8.TransactionModel>>);

  @override
  _i4.Future<_i2.TransactionSummary> getSummary(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, [startDate, endDate]),
            returnValue: _i4.Future<_i2.TransactionSummary>.value(
              _FakeTransactionSummary_0(
                this,
                Invocation.method(#getSummary, [startDate, endDate]),
              ),
            ),
          )
          as _i4.Future<_i2.TransactionSummary>);

  @override
  _i4.Future<List<_i9.DailySpend>> getDailySpend(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySpend, [startDate, endDate]),
            returnValue: _i4.Future<List<_i9.DailySpend>>.value(
              <_i9.DailySpend>[],
            ),
          )
          as _i4.Future<List<_i9.DailySpend>>);

  @override
  _i4.Future<List<_i10.CategorySpend>> getCategorySpend(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCategorySpend, [startDate, endDate]),
            returnValue: _i4.Future<List<_i10.CategorySpend>>.value(
              <_i10.CategorySpend>[],
            ),
          )
          as _i4.Future<List<_i10.CategorySpend>>);

  @override
  _i4.Future<int> reassignCategory(int? oldCategoryId, int? newCategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#reassignCategory, [
              oldCategoryId,
              newCategoryId,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
